<a href="https://colab.research.google.com/github/YQ617/code-samples/blob/Data-Analysis-and-Visualization/Yanfei_Qin_Participation_Activity_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Participation Activity 5
### Name: Yanfei Qin
### PennKey: yfqin
### PennID: 51386260

In [ ]:
numbers = [1, 2, 3]

In [ ]:
list(filter(lambda x: x > 1, numbers))

[2, 3]

## Activity 4: Calculate number of lines in a file
described on slide 23 of Lecture 4. You need to implement 3 functions which all achieve the same purpose of counting the number of lines in a file but each uses a different method to read contents of the file. (6 points).

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving sonnet29.txt to sonnet29.txt


In [ ]:
test_file = open('sonnet29.txt')

Function 1: count_read()

In [ ]:
def count_read(file_path):
    numb_line = 0
    test_file = open(file_path)
    test_file.seek(0)

    content = test_file.read()
    
    numb_line += content.count('\n') 
        
    print('The number of lines in the file is ' + str(numb_line))

In [ ]:
file_path = input("Enter the file path: ")
count_read(file_path)

Enter the file path: /content/sonnet29.txt
The number of lines in the file is 4


Function 2: count_readline()

In [ ]:
def count_readline(file_path):
    content_line = []
    test_file = open(file_path)
    test_file.seek(0)

    while True:
        line = test_file.readline()
        if line not in content_line and len(line)>0:
            content_line.append(line)
        else:
            break

    print('The number of lines in the file is ' + str(len(content_line)))

In [ ]:
file_path = input("Enter the file path: ")
count_readline(file_path)

Enter the file path: /content/sonnet29.txt
The number of lines in the file is 4


Function 3: count_readlines()

In [ ]:
def count_readlines(file_path):
    test_file = open(file_path)
    test_file.seek(0)
    len_line = len(test_file.readlines())
    print('The number of lines in the file is ' + str(len_line))

In [ ]:
file_path = input("Enter the file path: ")
count_readlines(file_path)

Enter the file path: /content/sonnet29.txt
The number of lines in the file is 4


## Activity 5: Modifying contents of a file
described on slide 25 of Lecture 4. (4 points)

In [ ]:
def modify_line(file, num_of_line, new_line):
    content = open(file, 'r').readlines()
    content[num_of_line] = new_line
    new_file = open(file, 'w')
    new_file.writelines(content)
    new_file.close()

In [ ]:
modify_line('sonnet29.txt', 1, 'I along with my spirit enjoy my outcast state,\n')

In [ ]:
modify_line('sonnet29.txt', 3, 'And look upon myself and bless my fate,\n')

In [ ]:
new_test_file = open('sonnet29.txt')
new_test_file.readlines()

["When, in disgrace with fortune and men's eyes,\n",
 'I along with my spirit enjoy my outcast state,\n',
 'And trouble deaf heaven with bootless cries,\n',
 'And look upon myself and bless my fate,\n']

### Activity 1: Read and write employee data from a csv using csv reader and writer
 described on slide 6 of Lecture 5.  (8 points)

In [ ]:
import csv
files.upload()

Saving employee.csv to employee.csv


{'employee.csv': b'EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,BONUS_PAY,MANAGER_ID,DEPARTMENT_ID\n198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600, - ,124,50\n199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600, - ,124,50\n200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400, - ,101,10\n201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000, - ,100,20\n202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000, - ,201,20\n203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500, - ,101,40\n204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000, - ,101,70\n205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008, - ,101,110\n206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300, - ,205,110\n100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000, - , - ,90\n101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000, - ,100,90\n102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17

In [ ]:
EmployeeFile = open('employee.csv')
EmployeeReader = csv.reader(EmployeeFile)

In [ ]:
for row in EmployeeReader:
  print('Row #'+ str(EmployeeReader.line_num)+' '+str(row))

Row #1 ['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER', 'HIRE_DATE', 'JOB_ID', 'SALARY', 'BONUS_PAY', 'MANAGER_ID', 'DEPARTMENT_ID']
Row #2 ['198', 'Donald', 'OConnell', 'DOCONNEL', '650.507.9833', '21-JUN-07', 'SH_CLERK', '2600', ' - ', '124', '50']
Row #3 ['199', 'Douglas', 'Grant', 'DGRANT', '650.507.9844', '13-JAN-08', 'SH_CLERK', '2600', ' - ', '124', '50']
Row #4 ['200', 'Jennifer', 'Whalen', 'JWHALEN', '515.123.4444', '17-SEP-03', 'AD_ASST', '4400', ' - ', '101', '10']
Row #5 ['201', 'Michael', 'Hartstein', 'MHARTSTE', '515.123.5555', '17-FEB-04', 'MK_MAN', '13000', ' - ', '100', '20']
Row #6 ['202', 'Pat', 'Fay', 'PFAY', '603.123.6666', '17-AUG-05', 'MK_REP', '6000', ' - ', '201', '20']
Row #7 ['203', 'Susan', 'Mavris', 'SMAVRIS', '515.123.7777', '07-JUN-02', 'HR_REP', '6500', ' - ', '101', '40']
Row #8 ['204', 'Hermann', 'Baer', 'HBAER', '515.123.8888', '07-JUN-02', 'PR_REP', '10000', ' - ', '101', '70']
Row #9 ['205', 'Shelley', 'Higgins', 'SHIGGINS', '515.

In [ ]:
EmployeeFile = open('employee.csv')
EmployeeReader = csv.reader(EmployeeFile)
next(EmployeeReader)
for row in EmployeeReader:
  print(str(row[5]))

21-JUN-07
13-JAN-08
17-SEP-03
17-FEB-04
17-AUG-05
07-JUN-02
07-JUN-02
07-JUN-02
07-JUN-02
17-JUN-03
21-SEP-05
13-JAN-01
03-JAN-06
21-MAY-07
25-JUN-05
05-FEB-06
07-FEB-07
17-AUG-02
16-AUG-02
28-SEP-05
30-SEP-05
07-MAR-06
07-DEC-07
07-DEC-02
18-MAY-03
24-DEC-05
24-JUL-05
15-NOV-06
10-AUG-07
18-JUL-04
10-APR-05
01-MAY-03
10-OCT-05
16-NOV-07
16-JUL-05
28-SEP-06
14-JAN-07
08-MAR-08
20-AUG-05
30-OCT-05
16-FEB-05
10-APR-07
14-JUN-04
26-AUG-06
12-DEC-07
06-FEB-08
14-JUL-03
26-OCT-05
12-FEB-06
06-APR-06


In [ ]:
EmployeeFile = open('employee.csv')
EmployeeReader = csv.reader(EmployeeFile)
next(EmployeeReader)
year_service = []
for row in EmployeeReader:
  year_service.append(str(21 - int((row[5][7] + row[5][8]))))

In [ ]:
year_service.insert(0,'YEARS_OF_SERVICE')
year_service

['YEARS_OF_SERVICE',
 '14',
 '13',
 '18',
 '17',
 '16',
 '19',
 '19',
 '19',
 '19',
 '18',
 '16',
 '20',
 '15',
 '14',
 '16',
 '15',
 '14',
 '19',
 '19',
 '16',
 '16',
 '15',
 '14',
 '19',
 '18',
 '16',
 '16',
 '15',
 '14',
 '17',
 '16',
 '18',
 '16',
 '14',
 '16',
 '15',
 '14',
 '13',
 '16',
 '16',
 '16',
 '14',
 '17',
 '15',
 '14',
 '13',
 '18',
 '16',
 '15',
 '15']

Here above I calculate the years of service for every employees and store these values into a list called year_service

In [ ]:
EmployeeFile = open('employee.csv')
EmployeeReader = csv.reader(EmployeeFile)
EmployeeData = list(EmployeeReader)

In [ ]:
for x, y in zip(EmployeeData, year_service):
    x.append(y)

Here above I have successfully append the years of service for each employee into the list of lists "EmployeeData" created from the original csv file. And I will store this list of lists into a new csv file in the following code cells.

In [ ]:
import csv
with open('new_employee.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(EmployeeData)

In [ ]:
import csv
NewEmployeeFile = open('new_employee.csv')
NewEmployeeReader = csv.reader(NewEmployeeFile)
next(NewEmployeeReader)
bonus_data = []
for row in NewEmployeeReader:
  if int(row[11]) < 5:
    row[8] = 12*0.25*int(row[7])
  elif int(row[11]) >= 5 and int(row[11]) < 10:
    row[8] = 12*0.35*int(row[7])
  elif int(row[11]) >= 10 and int(row[11]) < 15:
    row[8] = 12*0.45*int(row[7])
  elif int(row[11]) >= 15 and int(row[11]) < 20:
    row[8] = 12*0.75*int(row[7])
  elif int(row[11]) >= 20 and int(row[11]) <= 25:
    row[8] = 12*1*int(row[7])
  bonus_data.append(row[8])

In [ ]:
sum(bonus_data)

2682204.0

The above number 2682204.0 is the total amount of bonus salaries would given out if executing the HR's bonus plan. The amount is over $2 million budget that is offered by the finance department, so we do need a new bonus plan.

In [ ]:
import csv
NewEmployeeFile = open('new_employee.csv')
NewEmployeeReader = csv.reader(NewEmployeeFile)
row1 = next(NewEmployeeReader)

In [ ]:
import csv
NewEmployeeFile = open('new_employee.csv')
NewEmployeeReader = csv.reader(NewEmployeeFile)
print('Row #1'+str(row1))
next(NewEmployeeReader)
new_bonus_data = []
for row in NewEmployeeReader:
  if int(row[11]) < 5:
    row[8] = 12*(0.25-0.184)*int(row[7]) 
  elif int(row[11]) >= 5 and int(row[11]) < 10:
    row[8] = 12*(0.35-0.184)*int(row[7])
  elif int(row[11]) >= 10 and int(row[11]) < 15:
    row[8] = 12*(0.45-0.184)*int(row[7])
  elif int(row[11]) >= 15 and int(row[11]) < 20:
    row[8] = 12*(0.75-0.184)*int(row[7])
  elif int(row[11]) >= 20 and int(row[11]) <= 25:
    row[8] = 12*(1-0.184)*int(row[7])
  new_bonus_data.append(row[8])
  print('Row #'+ str(NewEmployeeReader.line_num)+' '+str(row))

Row #1['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER', 'HIRE_DATE', 'JOB_ID', 'SALARY', 'BONUS_PAY', 'MANAGER_ID', 'DEPARTMENT_ID', 'YEARS_OF_SERVICE']
Row #2 ['198', 'Donald', 'OConnell', 'DOCONNEL', '650.507.9833', '21-JUN-07', 'SH_CLERK', '2600', 8299.2, '124', '50', '14']
Row #3 ['199', 'Douglas', 'Grant', 'DGRANT', '650.507.9844', '13-JAN-08', 'SH_CLERK', '2600', 8299.2, '124', '50', '13']
Row #4 ['200', 'Jennifer', 'Whalen', 'JWHALEN', '515.123.4444', '17-SEP-03', 'AD_ASST', '4400', 29884.800000000003, '101', '10', '18']
Row #5 ['201', 'Michael', 'Hartstein', 'MHARTSTE', '515.123.5555', '17-FEB-04', 'MK_MAN', '13000', 88296.00000000001, '100', '20', '17']
Row #6 ['202', 'Pat', 'Fay', 'PFAY', '603.123.6666', '17-AUG-05', 'MK_REP', '6000', 40752.00000000001, '201', '20', '16']
Row #7 ['203', 'Susan', 'Mavris', 'SMAVRIS', '515.123.7777', '07-JUN-02', 'HR_REP', '6500', 44148.00000000001, '101', '40', '19']
Row #8 ['204', 'Hermann', 'Baer', 'HBAER', '515.123.8888', 

By extract the same constant 0.183 from all bonus %, we will get a total amount of 2003385, which is slightly above our budget. 

By extract the same constant 0.184 from all bonus %, we will get the closest total amount of 1999675.872 (rounded) to our 2M budget (if only consider a constant number that has a 3 decimal places).

I have already add the amount under “BONUS_PAY” column in employee.csv. Next, we simply need to create the new bonus scale and save it in a file called bonus_scale.csv.

In [ ]:
import csv
with open('bonus_scale.csv', 'w', newline='') as BonusFile:
    writer = csv.writer(BonusFile)
    writer.writerow(["Employee’s years of service",'Bonus as % of base annual salary'])
    writer.writerow(['0-5','6.6'])
    writer.writerow(['5-10','16.6'])
    writer.writerow(['10-15','26.6'])
    writer.writerow(['15-20','56.6'])
    writer.writerow(['20-25','81.6'])
    BonusFile.close()
file_bonus = open('bonus_scale.csv')
BonusReader = csv.reader(file_bonus)
for row in BonusReader:
  print(row)
#I do not know how to print out a exact same table as it shown in the question, but I indeed have created it:)

['Employee’s years of service', 'Bonus as % of base annual salary']
['0-5', '6.6']
['5-10', '16.6']
['10-15', '26.6']
['15-20', '56.6']
['20-25', '81.6']


## Activity 2: Using csv reader and writer
described on slide 8 of Lecture 5. (5 points)

In [ ]:
import csv
files.upload()

Saving student_grades.csv to student_grades.csv


{'student_grades.csv': b'student-id,ELA,Algebra,Chemistry,Economics,Physics,World History\n1234,B,A-,B+,A,B,A-\n3456,A-,A,B+,A,A-,C\n3971,B,B+,C,C+,B,A-\n4020,B-,A-,A,A-,B+,B\n5091,A,C+,B-,A,B+,A\n'}

In [ ]:
StudentGradesFile = open('student_grades.csv')
StudentGradesReader = csv.reader(StudentGradesFile)
GPA_LetterGrade_scale = {'A' : 4.0, 'A-': 3.75, 'B+': 3.5, 'B': 3.25, 'B-': 3, 'C+': 2.75, 'C': 2.5, 'C-': 2.25, 'F': 0}
name_list = []
GPA_list = []
for row in list(StudentGradesReader)[1:]:
  name_list.append(str(row[0]))
  Student_Avg_GPA = (GPA_LetterGrade_scale[row[1]]+GPA_LetterGrade_scale[row[2]]+GPA_LetterGrade_scale[row[3]]+GPA_LetterGrade_scale[row[4]]+GPA_LetterGrade_scale[row[5]]+GPA_LetterGrade_scale[row[6]])/6
  GPA_list.append(Student_Avg_GPA)

In [ ]:
name_list

['1234', '3456', '3971', '4020', '5091']

In [ ]:
GPA_list

[3.5833333333333335,
 3.5833333333333335,
 3.1666666666666665,
 3.5416666666666665,
 3.5416666666666665]

In [ ]:
name_GPA = dict(zip(name_list,GPA_list))
name_GPA

{'1234': 3.5833333333333335,
 '3456': 3.5833333333333335,
 '3971': 3.1666666666666665,
 '4020': 3.5416666666666665,
 '5091': 3.5416666666666665}

In [ ]:
import csv
GPA_file = open('Student_GPA_new_file.tsv','w')
csvWriter = csv.writer(GPA_file,delimiter='\t',lineterminator='\n\n\n')
csvWriter.writerow(['student_name','student_GPA'])
csvWriter.writerow(['1234','3.5833333333333335'])
csvWriter.writerow(['3456','3.5833333333333335'])
csvWriter.writerow(['4020','3.5416666666666665'])
csvWriter.writerow(['5091','3.5416666666666665'])
csvWriter.writerow(['3971','3.1666666666666665'])
GPA_file.close()

In [ ]:
file1 = open('Student_GPA_new_file.tsv')
outputReader = csv.reader(file1)
for row in outputReader:
    print(row)

['student_name\tstudent_GPA']
[]
[]
['1234\t3.5833333333333335']
[]
[]
['3456\t3.5833333333333335']
[]
[]
['4020\t3.5416666666666665']
[]
[]
['5091\t3.5416666666666665']
[]
[]
['3971\t3.1666666666666665']
[]
[]


## Activity 3: Read and write employee data from a csv using DictReader and DictWriter
 described on slide 11 of Lecture 5. (7 points)


In [ ]:
import csv
NewEmployeeFile = open('new_employee.csv')
NewEmployeeReader = csv.DictReader(NewEmployeeFile)
new_bonus_data = []
for row in NewEmployeeReader:
  if int(row['YEARS_OF_SERVICE']) < 5:
    row['BONUS_PAY'] = 12*0.25*int(row['SALARY']) 
  elif int(row['YEARS_OF_SERVICE']) >= 5 and int(row['YEARS_OF_SERVICE']) < 10:
    row['BONUS_PAY'] = 12*0.35*int(row['SALARY'])
  elif int(row['YEARS_OF_SERVICE']) >= 10 and int(row['YEARS_OF_SERVICE']) < 15:
    row['BONUS_PAY'] = 12*0.45*int(row['SALARY'])
  elif int(row['YEARS_OF_SERVICE']) >= 15 and int(row['YEARS_OF_SERVICE']) < 20:
    row['BONUS_PAY'] = 12*0.75*int(row['SALARY'])
  elif int(row['YEARS_OF_SERVICE']) >= 20 and int(row['YEARS_OF_SERVICE']) <= 25:
    row['BONUS_PAY'] = 12*1*int(row['SALARY'])
  new_bonus_data.append(row['BONUS_PAY'])
  print('Row #'+ str(NewEmployeeReader.line_num)+' '+str(row))

Row #2 OrderedDict([('EMPLOYEE_ID', '198'), ('FIRST_NAME', 'Donald'), ('LAST_NAME', 'OConnell'), ('EMAIL', 'DOCONNEL'), ('PHONE_NUMBER', '650.507.9833'), ('HIRE_DATE', '21-JUN-07'), ('JOB_ID', 'SH_CLERK'), ('SALARY', '2600'), ('BONUS_PAY', 14040.000000000002), ('MANAGER_ID', '124'), ('DEPARTMENT_ID', '50'), ('YEARS_OF_SERVICE', '14')])
Row #3 OrderedDict([('EMPLOYEE_ID', '199'), ('FIRST_NAME', 'Douglas'), ('LAST_NAME', 'Grant'), ('EMAIL', 'DGRANT'), ('PHONE_NUMBER', '650.507.9844'), ('HIRE_DATE', '13-JAN-08'), ('JOB_ID', 'SH_CLERK'), ('SALARY', '2600'), ('BONUS_PAY', 14040.000000000002), ('MANAGER_ID', '124'), ('DEPARTMENT_ID', '50'), ('YEARS_OF_SERVICE', '13')])
Row #4 OrderedDict([('EMPLOYEE_ID', '200'), ('FIRST_NAME', 'Jennifer'), ('LAST_NAME', 'Whalen'), ('EMAIL', 'JWHALEN'), ('PHONE_NUMBER', '515.123.4444'), ('HIRE_DATE', '17-SEP-03'), ('JOB_ID', 'AD_ASST'), ('SALARY', '4400'), ('BONUS_PAY', 39600.0), ('MANAGER_ID', '101'), ('DEPARTMENT_ID', '10'), ('YEARS_OF_SERVICE', '18')])
Row

In [ ]:
sum(new_bonus_data)

2682204.0

So by using the csv.DictReader we stil find the total amount of bonus is over our budget, being 2,682,204.00 USD. So we need to again design a new bonus plan.

In [ ]:
import csv
NewEmployeeFile = open('new_employee.csv')
NewEmployeeReader = csv.DictReader(NewEmployeeFile)
new_bonus_data = []
for row in NewEmployeeReader:
  if int(row['YEARS_OF_SERVICE']) < 5:
    row['BONUS_PAY'] = 12*(0.25-0.184)*int(row['SALARY']) 
  elif int(row['YEARS_OF_SERVICE']) >= 5 and int(row['YEARS_OF_SERVICE']) < 10:
    row['BONUS_PAY'] = 12*(0.35-0.184)*int(row['SALARY'])
  elif int(row['YEARS_OF_SERVICE']) >= 10 and int(row['YEARS_OF_SERVICE']) < 15:
    row['BONUS_PAY'] = 12*(0.45-0.184)*int(row['SALARY'])
  elif int(row['YEARS_OF_SERVICE']) >= 15 and int(row['YEARS_OF_SERVICE']) < 20:
    row['BONUS_PAY'] = 12*(0.75-0.184)*int(row['SALARY'])
  elif int(row['YEARS_OF_SERVICE']) >= 20 and int(row['YEARS_OF_SERVICE']) <= 25:
    row['BONUS_PAY'] = 12*(1-0.184)*int(row['SALARY'])
  new_bonus_data.append(row['BONUS_PAY'])
  print('Row #'+ str(NewEmployeeReader.line_num)+' '+str(row))

Row #2 OrderedDict([('EMPLOYEE_ID', '198'), ('FIRST_NAME', 'Donald'), ('LAST_NAME', 'OConnell'), ('EMAIL', 'DOCONNEL'), ('PHONE_NUMBER', '650.507.9833'), ('HIRE_DATE', '21-JUN-07'), ('JOB_ID', 'SH_CLERK'), ('SALARY', '2600'), ('BONUS_PAY', 8299.2), ('MANAGER_ID', '124'), ('DEPARTMENT_ID', '50'), ('YEARS_OF_SERVICE', '14')])
Row #3 OrderedDict([('EMPLOYEE_ID', '199'), ('FIRST_NAME', 'Douglas'), ('LAST_NAME', 'Grant'), ('EMAIL', 'DGRANT'), ('PHONE_NUMBER', '650.507.9844'), ('HIRE_DATE', '13-JAN-08'), ('JOB_ID', 'SH_CLERK'), ('SALARY', '2600'), ('BONUS_PAY', 8299.2), ('MANAGER_ID', '124'), ('DEPARTMENT_ID', '50'), ('YEARS_OF_SERVICE', '13')])
Row #4 OrderedDict([('EMPLOYEE_ID', '200'), ('FIRST_NAME', 'Jennifer'), ('LAST_NAME', 'Whalen'), ('EMAIL', 'JWHALEN'), ('PHONE_NUMBER', '515.123.4444'), ('HIRE_DATE', '17-SEP-03'), ('JOB_ID', 'AD_ASST'), ('SALARY', '4400'), ('BONUS_PAY', 29884.800000000003), ('MANAGER_ID', '101'), ('DEPARTMENT_ID', '10'), ('YEARS_OF_SERVICE', '18')])
Row #5 OrderedDi

In [ ]:
sum(new_bonus_data)

1999675.872

So here we again find out the new bonus plan, by extracting 18.4% from all bonus percentages. Since I already shown the updated csv with new BONUS_PAY above, the only thing left is to create a new csv called "bonus_scale".

In [ ]:
import csv
BonusFile = open('bonus_scale.csv', 'w', newline='')
BonusDictWriter = csv.DictWriter(BonusFile, ["Employee’s years of service", 'Bonus as % of base annual salary'])
BonusDictWriter.writeheader()
BonusDictWriter.writerow({"Employee’s years of service": '0-5', 'Bonus as % of base annual salary': '6.6'})
BonusDictWriter.writerow({"Employee’s years of service": '5-10', 'Bonus as % of base annual salary': '16.6'})
BonusDictWriter.writerow({"Employee’s years of service": '10-15', 'Bonus as % of base annual salary': '26.6'})
BonusDictWriter.writerow({"Employee’s years of service": '15-20', 'Bonus as % of base annual salary': '56.6'})
BonusDictWriter.writerow({"Employee’s years of service": '20-25', 'Bonus as % of base annual salary': '81.6'})
BonusFile.close()
file_bonus = open('bonus_scale.csv')
BonusReader = csv.reader(file_bonus)
for row in BonusReader:
  print(row)

['Employee’s years of service', 'Bonus as % of base annual salary']
['0-5', '6.6']
['5-10', '16.6']
['10-15', '26.6']
['15-20', '56.6']
['20-25', '81.6']


## Activity 4: Review csv reader and writer
 described on slide 12. You need to answer 5 questions on that slide of Lecture 5. (5 points). 



Q1: What do you pass to csv.reader() and csv.writer() to create reader and writer objects?

A1: A csv file, or a tsv file if delimiter="\t" is written. Csv/tsv files are supposed to be opened using the open() function before passing to csv.reader() and csv.writer().

Q2: What modes do File objects for reader and writer objects need to be opened in?

A2: We need to open the file object in the following function: File_object = open(“NameofFile”, “Mode”)

For reader object, we do not need to enter any mode since it is reader object by default. If we really want to put it explicitly, it is 'r' to the place of "Mode" in the above function.

For writer object, we need to write 'w' to the place of "Mode" in the above function.

Q3: What method takes a list argument and writes it to a CSV file?

A3: write = csv.writer(); write.writerow()

Q4: What do the delimiter and lineterminator keyword arguments do?

A4: The delimiter, which is a comma by default for any CSV file, is the character that appears between cells on a row. The line terminator, which is a new line by default for any CSV file, is the character that comes at the end of a row. 

We can change the delimiter and line terminator characters to different values by using the delimiter and lineterminator keyword arguments with csv.writer().

Q5: What is the difference between reading a csv file using csv.reader() vs. reading it using csv.DictReader()?

A5: csv.reader() returns an iterable reader object of the csv file while csv.DictReader() reads a csv file as a dictionary and returns a dictionary for each row in the input file.